receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  otlp/honeycomb:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": apikey
  awsxray:
  awsemf:
    log_group_name: open-telemetry-test
    log_stream_name: metrics
    namespace: open-telemetry-test
    dimension_rollup_option: '1'
    log_retention: 60
  awscloudwatchlogs:
    log_group_name: open-telemetry-test
    log_stream_name: logs

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1888"
  zpages:
    endpoint: "0.0.0.0:55679"

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/honeycomb, awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/honeycomb, awsemf]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/honeycomb, awscloudwatchlogs]
