openapi: 3.1.0
info:
  version: 1.0.0
  title: PHP OpenTelemetry Test Application
  contact:
    email: jess@mintopia.net
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  description: |
    # Introduction

    This PHP application is designed to be an example of using OpenTelemetry inside an application to export metrics, logs
    and traces to any OpenTelemetry compatible provider.

    Open Telemetry is a vendor-neutral CNCF project for standardised observability. It is widely supported by all
    observability providers.

    ## Architecture

    The main application is a Laravel 12 application running in a docker container using FrankenPHP. There is a scheduler
    container running a task that exports metrics every minute. The metrics themselves are stored in a redis compatible
    cache, eg. Redis, ElastiCache, Valkey.

    An Open Telemetry Collector container is running as a sidecar and takes the metrics and pushes them based on the
    configuration in `otel-collector-config.yaml` in the root. This is using the
    [AWS Open Telemetry Collector](https://github.com/aws-observability/aws-otel-collector)
    as it allows easy submission of data to CloudWatch and X-Ray. The supplied configuration also has an example of sending
    data to [Honeycomb](https://www.honeycomb.io/).

    ## Metrics

    There are 3 metrics we export every minute.

    - `widget-count` - An Open Telemetry Counter. This can only go up and is incremented using the `/count` endpoint.
    - `widget-number` - An Open Telemetry Up Down Counter. This can be increased and decreased using the `/up` and `/down` endpoints.
    - `load` - An Open Telemetry Gauge. This can be set using the `/load` endpoint. It is intended to be used to simulate load on the application and to be used for autoscaling decisions.

    ## Technology Choices

    Laravel 12 was used as an easy to implement and understandable PHP framework for this. The Open Telemetry integration is
    custom written using the Open Telemetry SDK. I considered using the
    [Spatie Laravel Open Telemetry](https://spatie.be/docs/laravel-open-telemetry/v1/introduction) library, but found that
    it wasn't outputting OTLP HTTP JSON formatted requests to the OpenTelemetry collector.

    Laravel Octane and FrankenPHP are used for running the application. This would allow for high performance in production
    environments.

    PHPStan and PHP Code Beautifier and Fixer is used to ensure code quality and adherence to standards.

    API documentation is written as an OpenAPI specification, bundled and generated by Redocly.
servers:
  - url: https://opentelemetry/api/v1
tags:
  - name: General
    description: Endpoints that don't belong in other categories.
  - name: Metrics
    description: Endpoints relating to metrics.
  - name: Traces
    description: Endpoints relating to traces.
paths:
  /ping:
    get:
      tags:
        - General
      summary: Ping
      description: Returns basic information about the API and the current user. This will include your IP address, the API timestamp and the version.
      operationId: ping
      security:
        - {}
      responses:
        '200':
          description: API Ping Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
  /count:
    post:
      tags:
        - Metrics
      summary: Count
      description: Increases the `widget-count` metric by 1
      operationId: count
      security:
        - {}
      responses:
        '200':
          description: Metric Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricValue'
  /up:
    post:
      tags:
        - Metrics
      summary: Up
      description: Increases the `widget-numbers` metric by 1
      operationId: up
      security:
        - {}
      responses:
        '200':
          description: Metric Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricValue'
  /down:
    post:
      tags:
        - Metrics
      summary: Down
      description: Decreases the `widget-numbers` metric by 1
      operationId: down
      security:
        - {}
      responses:
        '200':
          description: Metric Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricValue'
  /load:
    put:
      tags:
        - Metrics
      summary: Load
      description: Sets the `load` metric to a specific value between 1 and 100.
      operationId: load
      security:
        - {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/load'
      responses:
        '200':
          description: Metric Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Load'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
  /delay:
    get:
      tags:
        - Traces
      summary: Delay
      description: Includes a child trace and delays execution for 1 second.
      operationId: delay
      security:
        - {}
      responses:
        '204':
          description: Successful Request
  /event:
    get:
      tags:
        - Traces
      summary: Event
      description: Records an event against the trace.
      operationId: event
      security:
        - {}
      responses:
        '204':
          description: Successful Request
components:
  schemas:
    Ping:
      type: object
      properties:
        timestamp:
          type: string
          examples:
            - '2023-10-03T14:41:31+00:00'
          format: date-time
          description: Current timestamp in ISO 8601 format
        version:
          type: string
          examples:
            - 1.0.0
          description: Version number of the API
        ip:
          type: string
          examples:
            - 127.0.0.1
            - '::1'
          format: ip
          description: IP address of client making requests
    MetricValue:
      type: object
      properties:
        value:
          type: integer
          examples:
            - 42
          description: The current value of the `widget-count` metric.
    load:
      type: object
      properties:
        load:
          type: integer
          description: The value to set the load metric to. This must be between 1 and 100.
          examples:
            - 42
    Load:
      type: object
      properties:
        load:
          type: integer
          examples:
            - 42
          description: The current value of the `load` metric.
  responses:
    UnprocessableEntity:
      description: The request could not be processed. You should check the body of the error for more details.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                examples:
                  - The given data was invalid.
              errors:
                type: object
                description: An object containing the errors for each field in the input
                examples:
                  - name:
                      - The name field is required
                      - The name field must be more than 8 characters
                    hostname:
                      - the hostname field is required
